// Package piv implements PIV/CAC client certificate validation primitives:
//
//   - ExtractUPN pulls the Microsoft UPN extension (OID 1.3.6.1.4.1.311.20.2.3)
//     from a parsed x509.Certificate. The UPN is the canonical federal-user
//     identifier on DoD CAC and PIV cards per FIPS PUB 201-2.
//
//   - TrustValidator wraps standard x509.Certificate.Verify with a pinned
//     DoD trust-anchor pool, an explicit expiry check, and an optional
//     assurance-level policy OID filter.
//
// AOID Objective 3 (TRD 03-06) consumes this primitive for AAL3
// passwordless authentication. AOEdge IL4+ deployments and the AOSentry
// FedRAMP-Moderate console reuse it.
//
// # Scope
//
// This package handles trust-anchor chain validation, leaf expiry, policy
// OID filtering, and UPN extraction. Revocation (CRL / OCSP) is NOT in
// scope; consumers MUST layer revocation separately (see
// platform/mtls/revocation, future).
//
// # Fixture testing
//
// All tests use synthetic PEM fixtures generated by the openssl recipe
// in testdata/README.md. Do NOT commit real DoD-issued certificates to
// this repository.
package piv
