// Package totp provides TOTP (RFC 6238) secret generation, validation, and
// bcrypt-hashed backup codes.
//
// Promoted from aodex-go/internal/auth/totp.go. The TOTP issuer name is now
// configurable via the package-level Issuer variable so platform consumers
// (AODex, eden-biz, AO ID, AOSentry, etc.) can rebrand authenticator-app
// entries without forking the package.
package totp

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"

	"github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
	"golang.org/x/crypto/bcrypt"
)

// Issuer is the TOTP issuer string shown in authenticator apps.
// Consumers may override this at process startup.
var Issuer = "AOC Platform"

const (
	// DefaultBackupCodeCount is the number of backup codes generated by
	// GenerateBackupCodes when count <= 0 is passed.
	DefaultBackupCodeCount = 10

	// BackupCodeLength is the number of hex characters per backup code.
	BackupCodeLength = 8
)

// GenerateSecret creates a new TOTP key for the given account name (typically
// an email address). RFC 6238 defaults: SHA1, 6 digits, 30-second period.
func GenerateSecret(accountName string) (*otp.Key, error) {
	key, err := totp.Generate(totp.GenerateOpts{
		Issuer:      Issuer,
		AccountName: accountName,
		Period:      30,
		Digits:      otp.DigitsSix,
		Algorithm:   otp.AlgorithmSHA1,
	})
	if err != nil {
		return nil, fmt.Errorf("generating TOTP secret: %w", err)
	}
	return key, nil
}

// GenerateProvisioningURI returns an otpauth:// URI suitable for QR code
// generation. The secret must be base32-encoded (as stored on the user row).
func GenerateProvisioningURI(secret, accountName string) string {
	uri := fmt.Sprintf("otpauth://totp/%s:%s?secret=%s&issuer=%s&algorithm=SHA1&digits=6&period=30",
		Issuer, accountName, secret, Issuer)
	if key, err := otp.NewKeyFromURL(uri); err == nil {
		return key.URL()
	}
	return uri
}

// Validate validates a 6-digit TOTP code against the given base32-encoded
// secret. Allows ±1 period skew (default in pquerna/otp) for clock drift.
func Validate(code, secret string) bool {
	return totp.Validate(code, secret)
}

// GenerateBackupCodes generates plain backup codes and their bcrypt hashes.
// plainCodes are shown once to the user; hashedCodes are persisted.
func GenerateBackupCodes(count int) (plainCodes, hashedCodes []string, err error) {
	if count <= 0 {
		count = DefaultBackupCodeCount
	}
	plainCodes = make([]string, count)
	hashedCodes = make([]string, count)
	for i := 0; i < count; i++ {
		bytes := make([]byte, BackupCodeLength/2)
		if _, err := rand.Read(bytes); err != nil {
			return nil, nil, fmt.Errorf("generating backup code: %w", err)
		}
		code := hex.EncodeToString(bytes)
		plainCodes[i] = code
		hash, err := bcrypt.GenerateFromPassword([]byte(code), bcrypt.DefaultCost)
		if err != nil {
			return nil, nil, fmt.Errorf("hashing backup code: %w", err)
		}
		hashedCodes[i] = string(hash)
	}
	return plainCodes, hashedCodes, nil
}

// VerifyBackupCode checks a provided code against a list of bcrypt-hashed
// backup codes. Returns the index of the matching code, or -1 if no match.
func VerifyBackupCode(code string, hashedCodes []string) int {
	for i, hash := range hashedCodes {
		if err := bcrypt.CompareHashAndPassword([]byte(hash), []byte(code)); err == nil {
			return i
		}
	}
	return -1
}
