package softkey

import (
	"context"
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/asn1"
	"errors"
	"math/big"
	"net/url"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/aocybersystems/eden-platform-go/platform/kms"
)

// -------- Fixtures --------
//
// All fixture data is produced from real Go crypto primitives at test setup —
// no LLM-generated bytes, no hand-rolled DER, no static test vectors.

// testCipher is a deterministic AES-256-GCM KMSCipher used purely for
// round-trip tests inside this package. The fixed 32-byte key makes failure
// reproducible. It is NOT for production use.
type testCipher struct{}

func (testCipher) Encrypt(_ context.Context, plaintext []byte) ([]byte, error) {
	block, err := aes.NewCipher([]byte("softkey-test-cipher-key-32-bytesx"[:32]))
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, err
	}
	return append(nonce, aead.Seal(nil, nonce, plaintext, nil)...), nil
}

func (testCipher) Decrypt(_ context.Context, ciphertext []byte) ([]byte, error) {
	block, err := aes.NewCipher([]byte("softkey-test-cipher-key-32-bytesx"[:32]))
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	if len(ciphertext) < aead.NonceSize() {
		return nil, errors.New("ciphertext too short")
	}
	nonce, body := ciphertext[:aead.NonceSize()], ciphertext[aead.NonceSize():]
	return aead.Open(nil, nonce, body, nil)
}

// resolverFromMap returns a Resolver that pulls (alg, wrapped) tuples from
// the supplied map keyed by canonical softkey URI.
type rowT struct {
	alg     string
	wrapped []byte
}

func resolverFromMap(m map[string]rowT) Resolver {
	return func(_ context.Context, keyID string) (string, []byte, error) {
		row, ok := m[keyID]
		if !ok {
			return "", nil, errors.New("not found")
		}
		return row.alg, row.wrapped, nil
	}
}

// mintAndStore produces a fresh keypair for alg, PKCS#8-marshals + wraps it,
// stores the row in m under the URI "softkey://aoid/keys/<uuid>", and returns
// the URI. Tests use this to set up the resolver map without leaking key
// minting logic into every test body.
func mintAndStore(t *testing.T, m map[string]rowT, alg string, uuid string) (uri string, pub crypto.PublicKey) {
	t.Helper()
	uri = "softkey://aoid/keys/" + uuid
	var priv crypto.Signer
	switch alg {
	case "ES256":
		k, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		require.NoError(t, err)
		priv = k
		pub = &k.PublicKey
	case "RS256":
		k, err := rsa.GenerateKey(rand.Reader, 2048)
		require.NoError(t, err)
		priv = k
		pub = &k.PublicKey
	default:
		t.Fatalf("mintAndStore: unsupported alg %q", alg)
	}
	pkcs8, err := x509.MarshalPKCS8PrivateKey(priv)
	require.NoError(t, err)
	wrapped, err := testCipher{}.Encrypt(context.Background(), pkcs8)
	require.NoError(t, err)
	m[uri] = rowT{alg: alg, wrapped: wrapped}
	return uri, pub
}

// -------- Tests --------

func TestSigner_ES256_RoundTrip(t *testing.T) {
	t.Run("happy_path_sign_and_verify_DER", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, pub := mintAndStore(t, m, "ES256", "11111111-1111-4111-8111-111111111111")
		u, err := url.Parse(uri)
		require.NoError(t, err)

		signer, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)
		require.Equal(t, "ES256", signer.SigningAlgorithm())
		require.Equal(t, uri, signer.KeyID())

		digest := sha256.Sum256([]byte("hello, softkey ES256"))
		sig, err := signer.Sign(rand.Reader, digest[:], crypto.SHA256)
		require.NoError(t, err)
		require.NotEmpty(t, sig)

		// DER → verify
		epub := pub.(*ecdsa.PublicKey)
		require.True(t, ecdsa.VerifyASN1(epub, digest[:], sig), "ES256 signature must verify against the public key")
	})
}

func TestSigner_RS256_RoundTrip(t *testing.T) {
	t.Run("happy_path_sign_and_verify_pkcs1v15", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, pub := mintAndStore(t, m, "RS256", "22222222-2222-4222-8222-222222222222")
		u, err := url.Parse(uri)
		require.NoError(t, err)

		signer, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)
		require.Equal(t, "RS256", signer.SigningAlgorithm())

		digest := sha256.Sum256([]byte("hello, softkey RS256"))
		sig, err := signer.Sign(rand.Reader, digest[:], crypto.SHA256)
		require.NoError(t, err)

		rpub := pub.(*rsa.PublicKey)
		require.NoError(t, rsa.VerifyPKCS1v15(rpub, crypto.SHA256, digest[:], sig))
	})
}

// TestSigner_ES256_WireFormatIsASN1DER is the load-bearing wire-format trap
// catcher. If softkey ever returns raw r||s for ES256 (e.g., a future
// refactor swaps SignASN1 for ecdsa.Sign), this test fails immediately —
// asn1.Unmarshal cannot parse 64 bytes of concatenated coordinates as a
// SEQUENCE { r INTEGER, s INTEGER }. The DER form is:
//
//	30 LL  02 LR <r bytes>  02 LS <s bytes>
//
// where LL is the total length, LR/LS are the r/s lengths, and r/s are
// possibly 32 or 33 bytes (33 if the high bit is set, requiring a 0x00
// pad to keep the INTEGER non-negative). Raw r||s would be exactly 64
// bytes and would not begin with 0x30 — the unmarshal call would error.
func TestSigner_ES256_WireFormatIsASN1DER(t *testing.T) {
	t.Run("sign_output_decodes_as_asn1_sequence_of_two_integers", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "ES256", "33333333-3333-4333-8333-333333333333")
		u, err := url.Parse(uri)
		require.NoError(t, err)

		signer, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)

		digest := sha256.Sum256([]byte("wire format probe"))
		sig, err := signer.Sign(rand.Reader, digest[:], crypto.SHA256)
		require.NoError(t, err)

		var ecdsaSig struct {
			R, S *big.Int
		}
		rest, err := asn1.Unmarshal(sig, &ecdsaSig)
		require.NoError(t, err, "softkey ES256 Sign must return ASN.1 DER (asn1.Unmarshal failed)")
		require.Empty(t, rest, "no trailing bytes after the SEQUENCE")
		require.NotNil(t, ecdsaSig.R)
		require.NotNil(t, ecdsaSig.S)
		require.Greater(t, ecdsaSig.R.Sign(), 0, "R must be positive")
		require.Greater(t, ecdsaSig.S.Sign(), 0, "S must be positive")
	})
}

func TestSigner_HealthCheck(t *testing.T) {
	ctx := context.Background()
	t.Run("ES256_healthcheck_passes", func(t *testing.T) {
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "ES256", "44444444-4444-4444-8444-444444444444")
		u, _ := url.Parse(uri)
		signer, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)
		require.NoError(t, signer.HealthCheck(ctx))
	})
	t.Run("RS256_healthcheck_passes", func(t *testing.T) {
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "RS256", "55555555-5555-4555-8555-555555555555")
		u, _ := url.Parse(uri)
		signer, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)
		require.NoError(t, signer.HealthCheck(ctx))
	})
}

func TestSigner_New_RejectsCorruptedWrappedBlob(t *testing.T) {
	t.Run("flipped_ciphertext_byte_fails_with_unwrap_error", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "ES256", "66666666-6666-4666-8666-666666666666")
		// Corrupt one byte in the middle of the wrapped blob (well past the
		// nonce so we're flipping ciphertext bytes covered by AEAD).
		corrupted := append([]byte(nil), m[uri].wrapped...)
		corrupted[len(corrupted)/2] ^= 0xFF
		m[uri] = rowT{alg: "ES256", wrapped: corrupted}

		u, _ := url.Parse(uri)
		_, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.Error(t, err)
		msg := strings.ToLower(err.Error())
		require.True(t,
			strings.Contains(msg, "unwrap") || strings.Contains(msg, "decrypt"),
			"error must mention unwrap/decrypt; got: %s", err.Error())
	})
}

func TestSigner_New_AlgRowMismatchIsRejected(t *testing.T) {
	t.Run("ECDSA_key_with_RS256_row_alg_errors", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "ES256", "77777777-7777-4777-8777-777777777777")
		// Tamper the row's alg metadata.
		m[uri] = rowT{alg: "RS256", wrapped: m[uri].wrapped}

		u, _ := url.Parse(uri)
		_, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.Error(t, err)
		require.Contains(t, err.Error(), "alg mismatch")
	})
}

func TestSigner_New_RejectsWrongScheme(t *testing.T) {
	t.Run("awskms_scheme_is_rejected_by_softkey_New", func(t *testing.T) {
		u, err := url.Parse("awskms:///some/key")
		require.NoError(t, err)
		_, err = New(context.Background(), u, Options{Resolver: resolverFromMap(map[string]rowT{}), WrapCipher: testCipher{}})
		require.Error(t, err)
		require.Contains(t, err.Error(), "invalid URI scheme")
	})
	t.Run("nil_URI_is_rejected", func(t *testing.T) {
		_, err := New(context.Background(), nil, Options{Resolver: resolverFromMap(map[string]rowT{}), WrapCipher: testCipher{}})
		require.Error(t, err)
		require.Contains(t, err.Error(), "nil URI")
	})
	t.Run("missing_resolver_is_rejected", func(t *testing.T) {
		u, _ := url.Parse("softkey://aoid/keys/x")
		_, err := New(context.Background(), u, Options{Resolver: nil, WrapCipher: testCipher{}})
		require.Error(t, err)
		require.Contains(t, err.Error(), "Resolver")
	})
	t.Run("missing_wrap_cipher_is_rejected", func(t *testing.T) {
		u, _ := url.Parse("softkey://aoid/keys/x")
		_, err := New(context.Background(), u, Options{Resolver: resolverFromMap(map[string]rowT{}), WrapCipher: nil})
		require.Error(t, err)
		require.Contains(t, err.Error(), "WrapCipher")
	})
}

func TestSigner_KeyID_IsCanonicalURI(t *testing.T) {
	t.Run("KeyID_returns_full_softkey_URI", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "ES256", "88888888-8888-4888-8888-888888888888")
		u, _ := url.Parse(uri)
		signer, err := New(ctx, u, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)
		require.Equal(t, uri, signer.KeyID())
		require.True(t, strings.HasPrefix(signer.KeyID(), "softkey://aoid/keys/"))
	})
}

func TestRegistry_SoftkeySchemeIsRegistered(t *testing.T) {
	t.Run("scheme_appears_in_RegisteredSchemes", func(t *testing.T) {
		schemes := kms.RegisteredSchemes()
		var found bool
		for _, s := range schemes {
			if s == "softkey" {
				found = true
				break
			}
		}
		require.True(t, found, "softkey scheme must be registered (have: %v)", schemes)
	})
}

func TestRegistry_BareOpenDirectsToOpenWithOptions(t *testing.T) {
	t.Run("kms_Open_returns_helpful_error", func(t *testing.T) {
		_, err := kms.Open(context.Background(), "softkey://aoid/keys/00000000-0000-0000-0000-000000000000")
		require.Error(t, err)
		require.Contains(t, err.Error(), "OpenWithOptions")
	})
}

func TestRegistry_OpenWithOptions_DispatchesToSoftkey(t *testing.T) {
	t.Run("kms_OpenWithOptions_with_softkey_Options_returns_a_signer", func(t *testing.T) {
		ctx := context.Background()
		m := map[string]rowT{}
		uri, _ := mintAndStore(t, m, "ES256", "99999999-9999-4999-8999-999999999999")
		signer, err := kms.OpenWithOptions(ctx, uri, Options{Resolver: resolverFromMap(m), WrapCipher: testCipher{}})
		require.NoError(t, err)
		require.NotNil(t, signer)
		require.Equal(t, "ES256", signer.SigningAlgorithm())
	})
	t.Run("kms_OpenWithOptions_wrong_opts_type_errors", func(t *testing.T) {
		_, err := kms.OpenWithOptions(context.Background(), "softkey://aoid/keys/x", "not-Options")
		require.Error(t, err)
		require.Contains(t, err.Error(), "softkey.Options")
	})
}
