// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createSSOConfig = `-- name: CreateSSOConfig :one
INSERT INTO sso_configs (company_id, provider, issuer_url, client_id, client_secret, metadata_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, provider, issuer_url, client_id, client_secret, metadata_url, is_active, created_at
`

type CreateSSOConfigParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	Provider     string    `json:"provider"`
	IssuerUrl    string    `json:"issuer_url"`
	ClientID     string    `json:"client_id"`
	ClientSecret string    `json:"client_secret"`
	MetadataUrl  string    `json:"metadata_url"`
}

func (q *Queries) CreateSSOConfig(ctx context.Context, arg CreateSSOConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, createSSOConfig,
		arg.CompanyID,
		arg.Provider,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.MetadataUrl,
	)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.MetadataUrl,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, revoked, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked = false AND expires_at > now()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSSOConfig = `-- name: GetSSOConfig :one
SELECT id, company_id, provider, issuer_url, client_id, client_secret, metadata_url, is_active, created_at FROM sso_configs
WHERE company_id = $1 AND provider = $2 AND is_active = true
`

type GetSSOConfigParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Provider  string    `json:"provider"`
}

func (q *Queries) GetSSOConfig(ctx context.Context, arg GetSSOConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, getSSOConfig, arg.CompanyID, arg.Provider)
	var i SsoConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.MetadataUrl,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens SET revoked = true WHERE user_id = $1
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = true WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
