// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, name, slug, parent_company_id, company_type, inherited_role_cap, inherited_access_level, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, slug, parent_company_id, company_type, inherited_role_cap, inherited_access_level, settings, is_active, created_at, updated_at
`

type CreateCompanyParams struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Slug                 string          `json:"slug"`
	ParentCompanyID      pgtype.UUID     `json:"parent_company_id"`
	CompanyType          string          `json:"company_type"`
	InheritedRoleCap     *int32          `json:"inherited_role_cap"`
	InheritedAccessLevel *string         `json:"inherited_access_level"`
	Settings             json.RawMessage `json:"settings"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ParentCompanyID,
		arg.CompanyType,
		arg.InheritedRoleCap,
		arg.InheritedAccessLevel,
		arg.Settings,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentCompanyID,
		&i.CompanyType,
		&i.InheritedRoleCap,
		&i.InheritedAccessLevel,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHierarchyEntries = `-- name: DeleteHierarchyEntries :exec
DELETE FROM company_hierarchies WHERE descendant_id = $1
`

func (q *Queries) DeleteHierarchyEntries(ctx context.Context, descendantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHierarchyEntries, descendantID)
	return err
}

const getAncestors = `-- name: GetAncestors :many
SELECT ancestor_id, descendant_id, generations FROM company_hierarchies
WHERE descendant_id = $1
ORDER BY generations ASC
`

func (q *Queries) GetAncestors(ctx context.Context, descendantID uuid.UUID) ([]CompanyHierarchy, error) {
	rows, err := q.db.Query(ctx, getAncestors, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanyHierarchy{}
	for rows.Next() {
		var i CompanyHierarchy
		if err := rows.Scan(&i.AncestorID, &i.DescendantID, &i.Generations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, slug, parent_company_id, company_type, inherited_role_cap, inherited_access_level, settings, is_active, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentCompanyID,
		&i.CompanyType,
		&i.InheritedRoleCap,
		&i.InheritedAccessLevel,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDescendants = `-- name: GetDescendants :many
SELECT ancestor_id, descendant_id, generations FROM company_hierarchies
WHERE ancestor_id = $1
ORDER BY generations ASC
`

func (q *Queries) GetDescendants(ctx context.Context, ancestorID uuid.UUID) ([]CompanyHierarchy, error) {
	rows, err := q.db.Query(ctx, getDescendants, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanyHierarchy{}
	for rows.Next() {
		var i CompanyHierarchy
		if err := rows.Scan(&i.AncestorID, &i.DescendantID, &i.Generations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSelfAndDescendantIDs = `-- name: GetSelfAndDescendantIDs :many
SELECT descendant_id FROM company_hierarchies
WHERE ancestor_id = $1
`

func (q *Queries) GetSelfAndDescendantIDs(ctx context.Context, ancestorID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getSelfAndDescendantIDs, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var descendant_id uuid.UUID
		if err := rows.Scan(&descendant_id); err != nil {
			return nil, err
		}
		items = append(items, descendant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHierarchyEntry = `-- name: InsertHierarchyEntry :exec
INSERT INTO company_hierarchies (ancestor_id, descendant_id, generations)
VALUES ($1, $2, $3)
ON CONFLICT (ancestor_id, descendant_id) DO NOTHING
`

type InsertHierarchyEntryParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	Generations  int32     `json:"generations"`
}

func (q *Queries) InsertHierarchyEntry(ctx context.Context, arg InsertHierarchyEntryParams) error {
	_, err := q.db.Exec(ctx, insertHierarchyEntry, arg.AncestorID, arg.DescendantID, arg.Generations)
	return err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, slug, parent_company_id, company_type, inherited_role_cap, inherited_access_level, settings, is_active, created_at, updated_at FROM companies WHERE is_active = true ORDER BY name
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentCompanyID,
			&i.CompanyType,
			&i.InheritedRoleCap,
			&i.InheritedAccessLevel,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesForUser = `-- name: ListCompaniesForUser :many
SELECT c.id, c.name, c.slug, c.parent_company_id, c.company_type, c.inherited_role_cap, c.inherited_access_level, c.settings, c.is_active, c.created_at, c.updated_at FROM companies c
JOIN company_memberships cm ON cm.company_id = c.id
WHERE cm.user_id = $1 AND c.is_active = true
ORDER BY c.name
`

func (q *Queries) ListCompaniesForUser(ctx context.Context, userID uuid.UUID) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentCompanyID,
			&i.CompanyType,
			&i.InheritedRoleCap,
			&i.InheritedAccessLevel,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2, slug = $3, company_type = $4, inherited_role_cap = $5, inherited_access_level = $6, settings = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, parent_company_id, company_type, inherited_role_cap, inherited_access_level, settings, is_active, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Slug                 string          `json:"slug"`
	CompanyType          string          `json:"company_type"`
	InheritedRoleCap     *int32          `json:"inherited_role_cap"`
	InheritedAccessLevel *string         `json:"inherited_access_level"`
	Settings             json.RawMessage `json:"settings"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CompanyType,
		arg.InheritedRoleCap,
		arg.InheritedAccessLevel,
		arg.Settings,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentCompanyID,
		&i.CompanyType,
		&i.InheritedRoleCap,
		&i.InheritedAccessLevel,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
