// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consent_ledger.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getConsentEntry = `-- name: GetConsentEntry :one
SELECT id, household_id, principal_member_id, consenter_member_id, purpose, scope, consent_text_version, evidence, granted_at, revokes_id, created_at FROM consent_ledger WHERE id = $1
`

func (q *Queries) GetConsentEntry(ctx context.Context, id uuid.UUID) (ConsentLedger, error) {
	row := q.db.QueryRow(ctx, getConsentEntry, id)
	var i ConsentLedger
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.PrincipalMemberID,
		&i.ConsenterMemberID,
		&i.Purpose,
		&i.Scope,
		&i.ConsentTextVersion,
		&i.Evidence,
		&i.GrantedAt,
		&i.RevokesID,
		&i.CreatedAt,
	)
	return i, err
}

const insertConsentEntry = `-- name: InsertConsentEntry :one
INSERT INTO consent_ledger (
    household_id, principal_member_id, consenter_member_id,
    purpose, scope, consent_text_version, evidence, revokes_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, household_id, principal_member_id, consenter_member_id, purpose, scope, consent_text_version, evidence, granted_at, revokes_id, created_at
`

type InsertConsentEntryParams struct {
	HouseholdID        uuid.UUID       `json:"household_id"`
	PrincipalMemberID  uuid.UUID       `json:"principal_member_id"`
	ConsenterMemberID  uuid.UUID       `json:"consenter_member_id"`
	Purpose            string          `json:"purpose"`
	Scope              json.RawMessage `json:"scope"`
	ConsentTextVersion string          `json:"consent_text_version"`
	Evidence           json.RawMessage `json:"evidence"`
	RevokesID          pgtype.UUID     `json:"revokes_id"`
}

// Inserts a grant (revokes_id NULL) or revocation (revokes_id set).
func (q *Queries) InsertConsentEntry(ctx context.Context, arg InsertConsentEntryParams) (ConsentLedger, error) {
	row := q.db.QueryRow(ctx, insertConsentEntry,
		arg.HouseholdID,
		arg.PrincipalMemberID,
		arg.ConsenterMemberID,
		arg.Purpose,
		arg.Scope,
		arg.ConsentTextVersion,
		arg.Evidence,
		arg.RevokesID,
	)
	var i ConsentLedger
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.PrincipalMemberID,
		&i.ConsenterMemberID,
		&i.Purpose,
		&i.Scope,
		&i.ConsentTextVersion,
		&i.Evidence,
		&i.GrantedAt,
		&i.RevokesID,
		&i.CreatedAt,
	)
	return i, err
}

const latestConsentForPurpose = `-- name: LatestConsentForPurpose :one
SELECT id, household_id, principal_member_id, consenter_member_id, purpose, scope, consent_text_version, evidence, granted_at, revokes_id, created_at FROM consent_ledger
WHERE principal_member_id = $1 AND purpose = $2
ORDER BY granted_at DESC, created_at DESC
LIMIT 1
`

type LatestConsentForPurposeParams struct {
	PrincipalMemberID uuid.UUID `json:"principal_member_id"`
	Purpose           string    `json:"purpose"`
}

// Returns the most recent ledger row for (principal, purpose), regardless of
// whether it is a grant or revocation. Service-layer interprets the result.
func (q *Queries) LatestConsentForPurpose(ctx context.Context, arg LatestConsentForPurposeParams) (ConsentLedger, error) {
	row := q.db.QueryRow(ctx, latestConsentForPurpose, arg.PrincipalMemberID, arg.Purpose)
	var i ConsentLedger
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.PrincipalMemberID,
		&i.ConsenterMemberID,
		&i.Purpose,
		&i.Scope,
		&i.ConsentTextVersion,
		&i.Evidence,
		&i.GrantedAt,
		&i.RevokesID,
		&i.CreatedAt,
	)
	return i, err
}

const listConsentEntriesByPurpose = `-- name: ListConsentEntriesByPurpose :many
SELECT id, household_id, principal_member_id, consenter_member_id, purpose, scope, consent_text_version, evidence, granted_at, revokes_id, created_at FROM consent_ledger
WHERE purpose = $1
ORDER BY granted_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListConsentEntriesByPurposeParams struct {
	Purpose string `json:"purpose"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListConsentEntriesByPurpose(ctx context.Context, arg ListConsentEntriesByPurposeParams) ([]ConsentLedger, error) {
	rows, err := q.db.Query(ctx, listConsentEntriesByPurpose, arg.Purpose, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentLedger{}
	for rows.Next() {
		var i ConsentLedger
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.PrincipalMemberID,
			&i.ConsenterMemberID,
			&i.Purpose,
			&i.Scope,
			&i.ConsentTextVersion,
			&i.Evidence,
			&i.GrantedAt,
			&i.RevokesID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentEntriesForHousehold = `-- name: ListConsentEntriesForHousehold :many
SELECT id, household_id, principal_member_id, consenter_member_id, purpose, scope, consent_text_version, evidence, granted_at, revokes_id, created_at FROM consent_ledger
WHERE household_id = $1
ORDER BY granted_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListConsentEntriesForHouseholdParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListConsentEntriesForHousehold(ctx context.Context, arg ListConsentEntriesForHouseholdParams) ([]ConsentLedger, error) {
	rows, err := q.db.Query(ctx, listConsentEntriesForHousehold, arg.HouseholdID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentLedger{}
	for rows.Next() {
		var i ConsentLedger
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.PrincipalMemberID,
			&i.ConsenterMemberID,
			&i.Purpose,
			&i.Scope,
			&i.ConsentTextVersion,
			&i.Evidence,
			&i.GrantedAt,
			&i.RevokesID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentEntriesForPrincipal = `-- name: ListConsentEntriesForPrincipal :many
SELECT id, household_id, principal_member_id, consenter_member_id, purpose, scope, consent_text_version, evidence, granted_at, revokes_id, created_at FROM consent_ledger
WHERE principal_member_id = $1
ORDER BY granted_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListConsentEntriesForPrincipalParams struct {
	PrincipalMemberID uuid.UUID `json:"principal_member_id"`
	Limit             int32     `json:"limit"`
	Offset            int32     `json:"offset"`
}

func (q *Queries) ListConsentEntriesForPrincipal(ctx context.Context, arg ListConsentEntriesForPrincipalParams) ([]ConsentLedger, error) {
	rows, err := q.db.Query(ctx, listConsentEntriesForPrincipal, arg.PrincipalMemberID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentLedger{}
	for rows.Next() {
		var i ConsentLedger
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.PrincipalMemberID,
			&i.ConsenterMemberID,
			&i.Purpose,
			&i.Scope,
			&i.ConsentTextVersion,
			&i.Evidence,
			&i.GrantedAt,
			&i.RevokesID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
