// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDeviceToken = `-- name: CreateDeviceToken :exec
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, token) DO NOTHING
`

type CreateDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, createDeviceToken, arg.UserID, arg.Token, arg.Platform)
	return err
}

const deleteAllUserDeviceTokens = `-- name: DeleteAllUserDeviceTokens :exec
DELETE FROM device_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllUserDeviceTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserDeviceTokens, userID)
	return err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	return err
}

const getDeviceTokens = `-- name: GetDeviceTokens :many
SELECT id, user_id, token, platform, created_at FROM device_tokens WHERE user_id = $1
`

func (q *Queries) GetDeviceTokens(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
