// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encrypted_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM encrypted_credentials
WHERE company_id = $1 AND credential_type = $2
`

type DeleteCredentialParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	CredentialType string    `json:"credential_type"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.CompanyID, arg.CredentialType)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, company_id, credential_type, encrypted_value, blind_index, created_at, updated_at FROM encrypted_credentials
WHERE company_id = $1 AND credential_type = $2
`

type GetCredentialParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	CredentialType string    `json:"credential_type"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (EncryptedCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.CompanyID, arg.CredentialType)
	var i EncryptedCredential
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CredentialType,
		&i.EncryptedValue,
		&i.BlindIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByBlindIndex = `-- name: GetCredentialByBlindIndex :one
SELECT id, company_id, credential_type, encrypted_value, blind_index, created_at, updated_at FROM encrypted_credentials
WHERE blind_index = $1
`

func (q *Queries) GetCredentialByBlindIndex(ctx context.Context, blindIndex string) (EncryptedCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByBlindIndex, blindIndex)
	var i EncryptedCredential
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CredentialType,
		&i.EncryptedValue,
		&i.BlindIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialTypes = `-- name: ListCredentialTypes :many
SELECT credential_type FROM encrypted_credentials
WHERE company_id = $1
ORDER BY credential_type
`

func (q *Queries) ListCredentialTypes(ctx context.Context, companyID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCredentialTypes, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var credential_type string
		if err := rows.Scan(&credential_type); err != nil {
			return nil, err
		}
		items = append(items, credential_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO encrypted_credentials (company_id, credential_type, encrypted_value, blind_index)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, credential_type) DO UPDATE
SET encrypted_value = EXCLUDED.encrypted_value, blind_index = EXCLUDED.blind_index, updated_at = now()
`

type UpsertCredentialParams struct {
	CompanyID      uuid.UUID `json:"company_id"`
	CredentialType string    `json:"credential_type"`
	EncryptedValue []byte    `json:"encrypted_value"`
	BlindIndex     string    `json:"blind_index"`
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertCredential,
		arg.CompanyID,
		arg.CredentialType,
		arg.EncryptedValue,
		arg.BlindIndex,
	)
	return err
}
