// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addHouseholdMember = `-- name: AddHouseholdMember :one
INSERT INTO household_members (household_id, user_id, role, status, birthdate, capabilities)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, household_id, user_id, role, status, birthdate, capabilities, added_at, removed_at
`

type AddHouseholdMemberParams struct {
	HouseholdID  uuid.UUID       `json:"household_id"`
	UserID       uuid.UUID       `json:"user_id"`
	Role         string          `json:"role"`
	Status       string          `json:"status"`
	Birthdate    pgtype.Date     `json:"birthdate"`
	Capabilities json.RawMessage `json:"capabilities"`
}

func (q *Queries) AddHouseholdMember(ctx context.Context, arg AddHouseholdMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, addHouseholdMember,
		arg.HouseholdID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.Birthdate,
		arg.Capabilities,
	)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
	)
	return i, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (primary_contact_user_id, display_name, metadata)
VALUES ($1, $2, $3)
RETURNING id, primary_contact_user_id, display_name, metadata, created_at, updated_at
`

type CreateHouseholdParams struct {
	PrimaryContactUserID uuid.UUID       `json:"primary_contact_user_id"`
	DisplayName          string          `json:"display_name"`
	Metadata             json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.PrimaryContactUserID, arg.DisplayName, arg.Metadata)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.PrimaryContactUserID,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
DELETE FROM households WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHousehold, id)
	return err
}

const establishParentOfRecord = `-- name: EstablishParentOfRecord :one
INSERT INTO parent_of_record (child_member_id, parent_member_id)
VALUES ($1, $2)
RETURNING id, child_member_id, parent_member_id, established_at, revoked_at
`

type EstablishParentOfRecordParams struct {
	ChildMemberID  uuid.UUID `json:"child_member_id"`
	ParentMemberID uuid.UUID `json:"parent_member_id"`
}

func (q *Queries) EstablishParentOfRecord(ctx context.Context, arg EstablishParentOfRecordParams) (ParentOfRecord, error) {
	row := q.db.QueryRow(ctx, establishParentOfRecord, arg.ChildMemberID, arg.ParentMemberID)
	var i ParentOfRecord
	err := row.Scan(
		&i.ID,
		&i.ChildMemberID,
		&i.ParentMemberID,
		&i.EstablishedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, primary_contact_user_id, display_name, metadata, created_at, updated_at FROM households WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.PrimaryContactUserID,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdMember = `-- name: GetHouseholdMember :one
SELECT id, household_id, user_id, role, status, birthdate, capabilities, added_at, removed_at FROM household_members WHERE id = $1
`

func (q *Queries) GetHouseholdMember(ctx context.Context, id uuid.UUID) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, getHouseholdMember, id)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listChildrenForParent = `-- name: ListChildrenForParent :many
SELECT id, child_member_id, parent_member_id, established_at, revoked_at FROM parent_of_record
WHERE parent_member_id = $1 AND revoked_at IS NULL
ORDER BY established_at ASC
`

func (q *Queries) ListChildrenForParent(ctx context.Context, parentMemberID uuid.UUID) ([]ParentOfRecord, error) {
	rows, err := q.db.Query(ctx, listChildrenForParent, parentMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentOfRecord{}
	for rows.Next() {
		var i ParentOfRecord
		if err := rows.Scan(
			&i.ID,
			&i.ChildMemberID,
			&i.ParentMemberID,
			&i.EstablishedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdMembers = `-- name: ListHouseholdMembers :many
SELECT id, household_id, user_id, role, status, birthdate, capabilities, added_at, removed_at FROM household_members
WHERE household_id = $1 AND status != 'removed'
ORDER BY added_at ASC
`

func (q *Queries) ListHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]HouseholdMember, error) {
	rows, err := q.db.Query(ctx, listHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdMember{}
	for rows.Next() {
		var i HouseholdMember
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.Birthdate,
			&i.Capabilities,
			&i.AddedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsForUser = `-- name: ListHouseholdsForUser :many
SELECT h.id, h.primary_contact_user_id, h.display_name, h.metadata, h.created_at, h.updated_at FROM households h
JOIN household_members m ON m.household_id = h.id
WHERE m.user_id = $1 AND m.status != 'removed'
ORDER BY h.created_at DESC
`

func (q *Queries) ListHouseholdsForUser(ctx context.Context, userID uuid.UUID) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryContactUserID,
			&i.DisplayName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentsOfRecord = `-- name: ListParentsOfRecord :many
SELECT id, child_member_id, parent_member_id, established_at, revoked_at FROM parent_of_record
WHERE child_member_id = $1 AND revoked_at IS NULL
ORDER BY established_at ASC
`

func (q *Queries) ListParentsOfRecord(ctx context.Context, childMemberID uuid.UUID) ([]ParentOfRecord, error) {
	rows, err := q.db.Query(ctx, listParentsOfRecord, childMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentOfRecord{}
	for rows.Next() {
		var i ParentOfRecord
		if err := rows.Scan(
			&i.ID,
			&i.ChildMemberID,
			&i.ParentMemberID,
			&i.EstablishedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeHouseholdMember = `-- name: RemoveHouseholdMember :exec
UPDATE household_members
SET status = 'removed', removed_at = now()
WHERE id = $1
`

func (q *Queries) RemoveHouseholdMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeHouseholdMember, id)
	return err
}

const revokeParentOfRecord = `-- name: RevokeParentOfRecord :exec
UPDATE parent_of_record
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeParentOfRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeParentOfRecord, id)
	return err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET display_name = $2, metadata = $3, updated_at = now()
WHERE id = $1
RETURNING id, primary_contact_user_id, display_name, metadata, created_at, updated_at
`

type UpdateHouseholdParams struct {
	ID          uuid.UUID       `json:"id"`
	DisplayName string          `json:"display_name"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold, arg.ID, arg.DisplayName, arg.Metadata)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.PrimaryContactUserID,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHouseholdMemberRole = `-- name: UpdateHouseholdMemberRole :one
UPDATE household_members
SET role = $2, capabilities = $3
WHERE id = $1
RETURNING id, household_id, user_id, role, status, birthdate, capabilities, added_at, removed_at
`

type UpdateHouseholdMemberRoleParams struct {
	ID           uuid.UUID       `json:"id"`
	Role         string          `json:"role"`
	Capabilities json.RawMessage `json:"capabilities"`
}

func (q *Queries) UpdateHouseholdMemberRole(ctx context.Context, arg UpdateHouseholdMemberRoleParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, updateHouseholdMemberRole, arg.ID, arg.Role, arg.Capabilities)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
	)
	return i, err
}
