// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addHouseholdMember = `-- name: AddHouseholdMember :one
INSERT INTO platform_household_members (
    household_id, identity_id, role, status, birthdate,
    is_manager, is_account_owner, capabilities
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner
`

type AddHouseholdMemberParams struct {
	HouseholdID    uuid.UUID       `json:"household_id"`
	IdentityID     uuid.UUID       `json:"identity_id"`
	Role           string          `json:"role"`
	Status         string          `json:"status"`
	Birthdate      pgtype.Date     `json:"birthdate"`
	IsManager      bool            `json:"is_manager"`
	IsAccountOwner bool            `json:"is_account_owner"`
	Capabilities   json.RawMessage `json:"capabilities"`
}

func (q *Queries) AddHouseholdMember(ctx context.Context, arg AddHouseholdMemberParams) (PlatformHouseholdMember, error) {
	row := q.db.QueryRow(ctx, addHouseholdMember,
		arg.HouseholdID,
		arg.IdentityID,
		arg.Role,
		arg.Status,
		arg.Birthdate,
		arg.IsManager,
		arg.IsAccountOwner,
		arg.Capabilities,
	)
	var i PlatformHouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.IdentityID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
		&i.IsManager,
		&i.IsAccountOwner,
	)
	return i, err
}

const clearHouseholdAccountOwner = `-- name: ClearHouseholdAccountOwner :exec
UPDATE platform_household_members
SET is_account_owner = false
WHERE household_id = $1 AND is_account_owner AND status <> 'removed'
`

// Step 1 of an account_owner transfer: demote the current owner. Scoped to the
// household so a transfer can never touch another household's rows.
func (q *Queries) ClearHouseholdAccountOwner(ctx context.Context, householdID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearHouseholdAccountOwner, householdID)
	return err
}

const countHouseholdManagers = `-- name: CountHouseholdManagers :one
SELECT count(*) FROM platform_household_members
WHERE household_id = $1 AND is_manager AND status <> 'removed'
`

func (q *Queries) CountHouseholdManagers(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHouseholdManagers, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO platform_households (primary_contact_identity_id, display_name, metadata)
VALUES ($1, $2, $3)
RETURNING id, primary_contact_identity_id, display_name, metadata, created_at, updated_at
`

type CreateHouseholdParams struct {
	PrimaryContactIdentityID uuid.UUID       `json:"primary_contact_identity_id"`
	DisplayName              string          `json:"display_name"`
	Metadata                 json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (PlatformHousehold, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.PrimaryContactIdentityID, arg.DisplayName, arg.Metadata)
	var i PlatformHousehold
	err := row.Scan(
		&i.ID,
		&i.PrimaryContactIdentityID,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
DELETE FROM platform_households WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHousehold, id)
	return err
}

const establishParentOfRecord = `-- name: EstablishParentOfRecord :one
INSERT INTO platform_parent_of_record (child_member_id, parent_member_id)
VALUES ($1, $2)
RETURNING id, child_member_id, parent_member_id, established_at, revoked_at
`

type EstablishParentOfRecordParams struct {
	ChildMemberID  uuid.UUID `json:"child_member_id"`
	ParentMemberID uuid.UUID `json:"parent_member_id"`
}

func (q *Queries) EstablishParentOfRecord(ctx context.Context, arg EstablishParentOfRecordParams) (PlatformParentOfRecord, error) {
	row := q.db.QueryRow(ctx, establishParentOfRecord, arg.ChildMemberID, arg.ParentMemberID)
	var i PlatformParentOfRecord
	err := row.Scan(
		&i.ID,
		&i.ChildMemberID,
		&i.ParentMemberID,
		&i.EstablishedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveMembershipForIdentity = `-- name: GetActiveMembershipForIdentity :one
SELECT id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner FROM platform_household_members
WHERE identity_id = $1 AND status <> 'removed'
ORDER BY added_at ASC
LIMIT 1
`

// Clean read path: the first (oldest) active membership for an identity. Phase
// 0 assumes one household per identity; ordering keeps the choice deterministic
// if that ever changes.
func (q *Queries) GetActiveMembershipForIdentity(ctx context.Context, identityID uuid.UUID) (PlatformHouseholdMember, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipForIdentity, identityID)
	var i PlatformHouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.IdentityID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
		&i.IsManager,
		&i.IsAccountOwner,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, primary_contact_identity_id, display_name, metadata, created_at, updated_at FROM platform_households WHERE id = $1
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (PlatformHousehold, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i PlatformHousehold
	err := row.Scan(
		&i.ID,
		&i.PrimaryContactIdentityID,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdMember = `-- name: GetHouseholdMember :one
SELECT id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner FROM platform_household_members WHERE id = $1
`

func (q *Queries) GetHouseholdMember(ctx context.Context, id uuid.UUID) (PlatformHouseholdMember, error) {
	row := q.db.QueryRow(ctx, getHouseholdMember, id)
	var i PlatformHouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.IdentityID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
		&i.IsManager,
		&i.IsAccountOwner,
	)
	return i, err
}

const getMemberByHouseholdAndIdentity = `-- name: GetMemberByHouseholdAndIdentity :one
SELECT id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner FROM platform_household_members
WHERE household_id = $1 AND identity_id = $2 AND status <> 'removed'
`

type GetMemberByHouseholdAndIdentityParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	IdentityID  uuid.UUID `json:"identity_id"`
}

func (q *Queries) GetMemberByHouseholdAndIdentity(ctx context.Context, arg GetMemberByHouseholdAndIdentityParams) (PlatformHouseholdMember, error) {
	row := q.db.QueryRow(ctx, getMemberByHouseholdAndIdentity, arg.HouseholdID, arg.IdentityID)
	var i PlatformHouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.IdentityID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
		&i.IsManager,
		&i.IsAccountOwner,
	)
	return i, err
}

const listChildrenForParent = `-- name: ListChildrenForParent :many
SELECT id, child_member_id, parent_member_id, established_at, revoked_at FROM platform_parent_of_record
WHERE parent_member_id = $1 AND revoked_at IS NULL
ORDER BY established_at ASC
`

func (q *Queries) ListChildrenForParent(ctx context.Context, parentMemberID uuid.UUID) ([]PlatformParentOfRecord, error) {
	rows, err := q.db.Query(ctx, listChildrenForParent, parentMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformParentOfRecord{}
	for rows.Next() {
		var i PlatformParentOfRecord
		if err := rows.Scan(
			&i.ID,
			&i.ChildMemberID,
			&i.ParentMemberID,
			&i.EstablishedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdMembers = `-- name: ListHouseholdMembers :many
SELECT id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner FROM platform_household_members
WHERE household_id = $1 AND status <> 'removed'
ORDER BY added_at ASC
`

func (q *Queries) ListHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]PlatformHouseholdMember, error) {
	rows, err := q.db.Query(ctx, listHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformHouseholdMember{}
	for rows.Next() {
		var i PlatformHouseholdMember
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.IdentityID,
			&i.Role,
			&i.Status,
			&i.Birthdate,
			&i.Capabilities,
			&i.AddedAt,
			&i.RemovedAt,
			&i.IsManager,
			&i.IsAccountOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsForIdentity = `-- name: ListHouseholdsForIdentity :many
SELECT h.id, h.primary_contact_identity_id, h.display_name, h.metadata, h.created_at, h.updated_at FROM platform_households h
JOIN platform_household_members m ON m.household_id = h.id
WHERE m.identity_id = $1 AND m.status <> 'removed'
ORDER BY h.created_at DESC
`

func (q *Queries) ListHouseholdsForIdentity(ctx context.Context, identityID uuid.UUID) ([]PlatformHousehold, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformHousehold{}
	for rows.Next() {
		var i PlatformHousehold
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryContactIdentityID,
			&i.DisplayName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentsOfRecord = `-- name: ListParentsOfRecord :many
SELECT id, child_member_id, parent_member_id, established_at, revoked_at FROM platform_parent_of_record
WHERE child_member_id = $1 AND revoked_at IS NULL
ORDER BY established_at ASC
`

func (q *Queries) ListParentsOfRecord(ctx context.Context, childMemberID uuid.UUID) ([]PlatformParentOfRecord, error) {
	rows, err := q.db.Query(ctx, listParentsOfRecord, childMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformParentOfRecord{}
	for rows.Next() {
		var i PlatformParentOfRecord
		if err := rows.Scan(
			&i.ID,
			&i.ChildMemberID,
			&i.ParentMemberID,
			&i.EstablishedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeHouseholdMember = `-- name: RemoveHouseholdMember :exec
UPDATE platform_household_members
SET status = 'removed', removed_at = now()
WHERE id = $1
`

func (q *Queries) RemoveHouseholdMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeHouseholdMember, id)
	return err
}

const revokeParentOfRecord = `-- name: RevokeParentOfRecord :exec
UPDATE platform_parent_of_record
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeParentOfRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeParentOfRecord, id)
	return err
}

const setHouseholdAccountOwner = `-- name: SetHouseholdAccountOwner :one
UPDATE platform_household_members
SET is_account_owner = true
WHERE id = $2 AND household_id = $1 AND status <> 'removed'
RETURNING id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner
`

type SetHouseholdAccountOwnerParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	ID          uuid.UUID `json:"id"`
}

// Step 2 of an account_owner transfer: promote the named member. Household-
// scoped: the member id must belong to $1 or no row is updated.
func (q *Queries) SetHouseholdAccountOwner(ctx context.Context, arg SetHouseholdAccountOwnerParams) (PlatformHouseholdMember, error) {
	row := q.db.QueryRow(ctx, setHouseholdAccountOwner, arg.HouseholdID, arg.ID)
	var i PlatformHouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.IdentityID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
		&i.IsManager,
		&i.IsAccountOwner,
	)
	return i, err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE platform_households
SET display_name = $2, metadata = $3, updated_at = now()
WHERE id = $1
RETURNING id, primary_contact_identity_id, display_name, metadata, created_at, updated_at
`

type UpdateHouseholdParams struct {
	ID          uuid.UUID       `json:"id"`
	DisplayName string          `json:"display_name"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (PlatformHousehold, error) {
	row := q.db.QueryRow(ctx, updateHousehold, arg.ID, arg.DisplayName, arg.Metadata)
	var i PlatformHousehold
	err := row.Scan(
		&i.ID,
		&i.PrimaryContactIdentityID,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHouseholdMemberRole = `-- name: UpdateHouseholdMemberRole :one
UPDATE platform_household_members
SET role = $2, is_manager = $3, is_account_owner = $4, capabilities = $5
WHERE id = $1
RETURNING id, household_id, identity_id, role, status, birthdate, capabilities, added_at, removed_at, is_manager, is_account_owner
`

type UpdateHouseholdMemberRoleParams struct {
	ID             uuid.UUID       `json:"id"`
	Role           string          `json:"role"`
	IsManager      bool            `json:"is_manager"`
	IsAccountOwner bool            `json:"is_account_owner"`
	Capabilities   json.RawMessage `json:"capabilities"`
}

func (q *Queries) UpdateHouseholdMemberRole(ctx context.Context, arg UpdateHouseholdMemberRoleParams) (PlatformHouseholdMember, error) {
	row := q.db.QueryRow(ctx, updateHouseholdMemberRole,
		arg.ID,
		arg.Role,
		arg.IsManager,
		arg.IsAccountOwner,
		arg.Capabilities,
	)
	var i PlatformHouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.IdentityID,
		&i.Role,
		&i.Status,
		&i.Birthdate,
		&i.Capabilities,
		&i.AddedAt,
		&i.RemovedAt,
		&i.IsManager,
		&i.IsAccountOwner,
	)
	return i, err
}
