// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles_permissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
UPDATE company_memberships SET role_id = $3, updated_at = now()
WHERE company_id = $1 AND user_id = $2
`

type AssignRoleToUserParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.CompanyID, arg.UserID, arg.RoleID)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO company_memberships (company_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (company_id, user_id) DO NOTHING
`

type CreateMembershipParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.CompanyID, arg.UserID, arg.RoleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (company_id, name, description, level)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, name, description, level, is_system, created_at
`

type CreateRoleParams struct {
	CompanyID   pgtype.UUID `json:"company_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Level       int32       `json:"level"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.Level,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyAncestors = `-- name: GetCompanyAncestors :many
SELECT ch.ancestor_id as company_id, ch.generations,
    c.inherited_role_cap, c.inherited_access_level as access_level
FROM company_hierarchies ch
JOIN companies c ON c.id = ch.ancestor_id
WHERE ch.descendant_id = $1 AND ch.generations > 0
ORDER BY ch.generations ASC
`

type GetCompanyAncestorsRow struct {
	CompanyID        uuid.UUID `json:"company_id"`
	Generations      int32     `json:"generations"`
	InheritedRoleCap *int32    `json:"inherited_role_cap"`
	AccessLevel      *string   `json:"access_level"`
}

func (q *Queries) GetCompanyAncestors(ctx context.Context, descendantID uuid.UUID) ([]GetCompanyAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getCompanyAncestors, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompanyAncestorsRow{}
	for rows.Next() {
		var i GetCompanyAncestorsRow
		if err := rows.Scan(
			&i.CompanyID,
			&i.Generations,
			&i.InheritedRoleCap,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembership = `-- name: GetMembership :one
SELECT cm.id, cm.company_id, cm.user_id, cm.role_id, r.name as role_name, r.level as role_level, cm.permission_overrides
FROM company_memberships cm
JOIN roles r ON r.id = cm.role_id
WHERE cm.company_id = $1 AND cm.user_id = $2
`

type GetMembershipParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetMembershipRow struct {
	ID                  uuid.UUID `json:"id"`
	CompanyID           uuid.UUID `json:"company_id"`
	UserID              uuid.UUID `json:"user_id"`
	RoleID              uuid.UUID `json:"role_id"`
	RoleName            string    `json:"role_name"`
	RoleLevel           int32     `json:"role_level"`
	PermissionOverrides []byte    `json:"permission_overrides"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CompanyID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.RoleID,
		&i.RoleName,
		&i.RoleLevel,
		&i.PermissionOverrides,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, company_id, name, description, level, is_system, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.id, p.feature, p.action, p.resource, p.description FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN company_memberships cm ON cm.role_id = rp.role_id
WHERE cm.company_id = $1 AND cm.user_id = $2
`

type GetUserPermissionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Action,
			&i.Resource,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRole = `-- name: GetUserRole :one
SELECT r.id, r.company_id, r.name, r.description, r.level, r.is_system, r.created_at FROM roles r
JOIN company_memberships cm ON cm.role_id = r.id
WHERE cm.company_id = $1 AND cm.user_id = $2
`

type GetUserRoleParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.CompanyID, arg.UserID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPermissions = `-- name: ListAllPermissions :many
SELECT id, feature, action, resource, description FROM permissions ORDER BY feature, action
`

func (q *Queries) ListAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Action,
			&i.Resource,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT p.id, p.feature, p.action, p.resource, p.description FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) ListPermissionsByRole(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Action,
			&i.Resource,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByCompany = `-- name: ListRolesByCompany :many
SELECT id, company_id, name, description, level, is_system, created_at FROM roles
WHERE company_id = $1 OR is_system = true
ORDER BY level DESC
`

func (q *Queries) ListRolesByCompany(ctx context.Context, companyID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Level,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCompanyIDs = `-- name: ListUserCompanyIDs :many
SELECT company_id FROM company_memberships WHERE user_id = $1
`

func (q *Queries) ListUserCompanyIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserCompanyIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var company_id uuid.UUID
		if err := rows.Scan(&company_id); err != nil {
			return nil, err
		}
		items = append(items, company_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
