// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserIdentity = `-- name: DeleteUserIdentity :exec
DELETE FROM user_identities WHERE id = $1
`

func (q *Queries) DeleteUserIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserIdentity, id)
	return err
}

const getUserIdentityByEmail = `-- name: GetUserIdentityByEmail :one
SELECT id, user_id, provider, provider_sub, email, is_verified, display_name, avatar_url, raw_claims, created_at, updated_at FROM user_identities WHERE email = $1
`

func (q *Queries) GetUserIdentityByEmail(ctx context.Context, email *string) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByEmail, email)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.Email,
		&i.IsVerified,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIdentityByProviderSub = `-- name: GetUserIdentityByProviderSub :one
SELECT id, user_id, provider, provider_sub, email, is_verified, display_name, avatar_url, raw_claims, created_at, updated_at FROM user_identities WHERE provider = $1 AND provider_sub = $2
`

type GetUserIdentityByProviderSubParams struct {
	Provider    string `json:"provider"`
	ProviderSub string `json:"provider_sub"`
}

func (q *Queries) GetUserIdentityByProviderSub(ctx context.Context, arg GetUserIdentityByProviderSubParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByProviderSub, arg.Provider, arg.ProviderSub)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.Email,
		&i.IsVerified,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserIdentitiesByUser = `-- name: ListUserIdentitiesByUser :many
SELECT id, user_id, provider, provider_sub, email, is_verified, display_name, avatar_url, raw_claims, created_at, updated_at FROM user_identities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListUserIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listUserIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSub,
			&i.Email,
			&i.IsVerified,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.RawClaims,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserIdentity = `-- name: UpsertUserIdentity :one
INSERT INTO user_identities (user_id, provider, provider_sub, email, is_verified, display_name, avatar_url, raw_claims)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (provider, provider_sub) DO UPDATE SET
    email = EXCLUDED.email,
    is_verified = EXCLUDED.is_verified,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    raw_claims = EXCLUDED.raw_claims,
    updated_at = now()
RETURNING id, user_id, provider, provider_sub, email, is_verified, display_name, avatar_url, raw_claims, created_at, updated_at
`

type UpsertUserIdentityParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Provider    string    `json:"provider"`
	ProviderSub string    `json:"provider_sub"`
	Email       *string   `json:"email"`
	IsVerified  bool      `json:"is_verified"`
	DisplayName *string   `json:"display_name"`
	AvatarUrl   *string   `json:"avatar_url"`
	RawClaims   []byte    `json:"raw_claims"`
}

func (q *Queries) UpsertUserIdentity(ctx context.Context, arg UpsertUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, upsertUserIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSub,
		arg.Email,
		arg.IsVerified,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.RawClaims,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSub,
		&i.Email,
		&i.IsVerified,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
