// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, webhook_id, event_type, payload, status, status_code, response_body, attempts, next_retry_at, created_at
`

type CreateDeliveryParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	EventType string    `json:"event_type"`
	Payload   string    `json:"payload"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.WebhookID, arg.EventType, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.StatusCode,
		&i.ResponseBody,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (company_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, url, secret, events, active, consecutive_fails, created_at, updated_at
`

type CreateWebhookParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Url       string    `json:"url"`
	Secret    string    `json:"secret"`
	Events    []string  `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.CompanyID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.ConsecutiveFails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, webhook_id, event_type, payload, status, status_code, response_body, attempts, next_retry_at, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.StatusCode,
		&i.ResponseBody,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDeliveries = `-- name: GetPendingDeliveries :many
SELECT id, webhook_id, event_type, payload, status, status_code, response_body, attempts, next_retry_at, created_at FROM webhook_deliveries
WHERE status IN ('pending', 'failed') AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) GetPendingDeliveries(ctx context.Context) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, getPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.StatusCode,
			&i.ResponseBody,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, company_id, url, secret, events, active, consecutive_fails, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.ConsecutiveFails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailureCount = `-- name: IncrementFailureCount :one
UPDATE webhooks SET consecutive_fails = consecutive_fails + 1, updated_at = now()
WHERE id = $1
RETURNING consecutive_fails
`

func (q *Queries) IncrementFailureCount(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailureCount, id)
	var consecutive_fails int32
	err := row.Scan(&consecutive_fails)
	return consecutive_fails, err
}

const listDeliveriesByWebhook = `-- name: ListDeliveriesByWebhook :many
SELECT id, webhook_id, event_type, payload, status, status_code, response_body, attempts, next_retry_at, created_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveriesByWebhookParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListDeliveriesByWebhook(ctx context.Context, arg ListDeliveriesByWebhookParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByWebhook, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.StatusCode,
			&i.ResponseBody,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedDeliveriesForRetry = `-- name: ListFailedDeliveriesForRetry :many
SELECT id, webhook_id, event_type, payload, status, status_code, response_body, attempts, next_retry_at, created_at FROM webhook_deliveries
WHERE status = 'failed' AND attempts < $1
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) ListFailedDeliveriesForRetry(ctx context.Context, attempts int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listFailedDeliveriesForRetry, attempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.StatusCode,
			&i.ResponseBody,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByCompany = `-- name: ListWebhooksByCompany :many
SELECT id, company_id, url, secret, events, active, consecutive_fails, created_at, updated_at FROM webhooks WHERE company_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByCompany(ctx context.Context, companyID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.ConsecutiveFails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFailureCount = `-- name: ResetFailureCount :exec
UPDATE webhooks SET consecutive_fails = 0, updated_at = now() WHERE id = $1
`

func (q *Queries) ResetFailureCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailureCount, id)
	return err
}

const updateDelivery = `-- name: UpdateDelivery :exec
UPDATE webhook_deliveries
SET status = $2, status_code = $3, response_body = $4, next_retry_at = $5, attempts = attempts + 1
WHERE id = $1
`

type UpdateDeliveryParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	StatusCode   int32              `json:"status_code"`
	ResponseBody string             `json:"response_body"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) error {
	_, err := q.db.Exec(ctx, updateDelivery,
		arg.ID,
		arg.Status,
		arg.StatusCode,
		arg.ResponseBody,
		arg.NextRetryAt,
	)
	return err
}

const updateWebhookStatus = `-- name: UpdateWebhookStatus :exec
UPDATE webhooks SET active = $2, updated_at = now() WHERE id = $1
`

type UpdateWebhookStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) UpdateWebhookStatus(ctx context.Context, arg UpdateWebhookStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookStatus, arg.ID, arg.Active)
	return err
}
